# Generated by Django 3.2.6 on 2021-08-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('A', 'Accepted'), ('C', 'Complete'), ('R', 'Rejected')], default='N', max_length=1),
            preserve_default=False,
        ),
    ]
