# Generated by Django 3.2.6 on 2021-08-18 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0002_issue_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='x',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='y',
            new_name='longitude',
        ),
    ]
