# Generated by Django 3.2.6 on 2021-08-18 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0003_auto_20210818_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
