# Generated by Django 3.2.6 on 2021-08-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0005_auto_20210825_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='image',
            new_name='image_before',
        ),
        migrations.AddField(
            model_name='issue',
            name='image_after',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
