# Generated by Django 3.2.6 on 2021-08-27 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0008_user_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
