# Generated by Django 3.2.6 on 2021-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fix', '0010_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.CharField(choices=[('R', 'Rookie'), ('S', 'Seasoned'), ('P', 'Pro')], max_length=1),
        ),
    ]
